/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package br.org.cesar.discordtime.apkanalyzer

import kotlin.test.Test
import kotlin.test.assertNotNull

class MainAppTest {
}
